services:
  authentication:
    build: ./n708-authentication
    ports:
      - "5001:5001"
    env_file:
      - ./n708-authentication/.env
    volumes:
      - authentication-data:/app/data
    restart: unless-stopped

  ticket:
    build: ./n708-ticket
    ports:
      - "5002:5002"
    env_file:
      - ./n708-ticket/.env
    volumes:
      - ticket-data:/app/data
    restart: unless-stopped

  feedback:
    build: ./n708-feedback
    ports:
      - "5003:5003"
    env_file:
      - ./n708-feedback/.env
    volumes:
      - feedback-data:/app/data
    restart: unless-stopped

  orchestrator:
    build: ./n708-orchestrator
    ports:
      - "5000:5000"
    env_file:
      - ./n708-orchestrator/.env
    depends_on:
      - authentication
      - ticket
      - feedback
    restart: unless-stopped

volumes:
  authentication-data:
  ticket-data:
  feedback-data:
