version: '3.8'

services:
  authentication:
    build: ./n708-authentication
    ports:
      - "5001:5001"
    env_file:
      - ./n708-authentication/.env
    volumes:
      - authentication-data:/app/data
    restart: unless-stopped
    container_name: authentication

  ticket:
    build: ./n708-ticket
    ports:
      - "5002:5002"
    env_file:
      - ./n708-ticket/.env
    volumes:
      - ticket-data:/app/data
    restart: unless-stopped
    container_name: ticket

  feedback:
    build: ./n708-feedback
    ports:
      - "5003:5003"
    env_file:
      - ./n708-feedback/.env
    volumes:
      - feedback-data:/app/data
    restart: unless-stopped
    container_name: feedback

  orchestrator:
    build: ./n708-orchestrator
    ports:
      - "5000:5000"
    env_file:
      - ./n708-orchestrator/.env
    depends_on:
      - authentication
      - ticket
      - feedback
    restart: unless-stopped
    container_name: orchestrator

volumes:
  authentication-data:
    name: authentication-data
  ticket-data:
    name: ticket-data
  feedback-data:
    name: feedback-data

networks:
  default:
    name: n708-backend-network
